INSERT INTO ESTUDIANTES (NOMBRE, APELLIDO)
VALUES ('ALEJANDRO', 'CAMACHO');

INSERT INTO ESTUDIANTES (NOMBRE, APELLIDO)
VALUES ('NOE', 'GOMEZ');

INSERT INTO ESTUDIANTES (NOMBRE, APELLIDO)
VALUES ('MARIA', 'PIEDRAS');