INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, ENROLADO, ID_CURSO, TELEFONO)
VALUES ('Jorge','Camacho','FALSE',1, 12345);

INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, ENROLADO, ID_CURSO, TELEFONO)
VALUES ('Alejandro','Camacho', 'TRUE',2, 54321);

INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, ENROLADO, ID_CURSO, TELEFONO)
VALUES ('Araceli','Piñeda', 'TRUE',3, 23594);
