INSERT INTO ESTUDIANTE(NOMBRE, APELLIDO, ENROLADO, ID_CURSO, TELEFONO)
VALUES ('ANGEL','BECERRIL', 'TRUE',1,722935);

INSERT INTO ESTUDIANTE(NOMBRE, APELLIDO, ENROLADO, ID_CURSO, TELEFONO)
VALUES ('NOE','RESENDIZ', 'TRUE',2,12345);

INSERT INTO ESTUDIANTE(NOMBRE, APELLIDO, ENROLADO, ID_CURSO, TELEFONO)
VALUES ('JAVIER','FLORES', 'TRUE',1,54321);